/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package chat.system.gui;

import chat.system.objects.ChatConnection;
import chat.system.objects.ChatLog;
import chat.system.objects.ChatMessage;
import chat.system.objects.ChatPerson;
import chat.system.objects.ServerMessage;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.UnknownHostException;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jon
 */
public class MainGUI extends javax.swing.JFrame implements Observer {

    ChatConnection connection;
    ChatLog log;
    PeopleList people;

    /**
     * Creates new form MainGUI
     */
    public MainGUI() throws UnknownHostException, IOException {
        initComponents();
        initConnection();
        log = new ChatLog(new FileOutputStream(new File("chat.log")));
        mainTextArea.setLineWrap(true);
        mainTextArea.setWrapStyleWord(true);
        people = new PeopleList(peopleList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        messageTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainTextArea = new javax.swing.JTextArea();
        sendButton = new javax.swing.JButton();
        statusBarLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        peopleList = new javax.swing.JList();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        changeUsernameMenuItem = new javax.swing.JMenuItem();
        changeServerMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chat");

        messageTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                messageTextFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                messageTextFieldKeyTyped(evt);
            }
        });

        mainTextArea.setEditable(false);
        mainTextArea.setColumns(20);
        mainTextArea.setRows(5);
        jScrollPane1.setViewportView(mainTextArea);

        sendButton.setText("Send");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        statusBarLabel.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        statusBarLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        statusBarLabel.setText("Ready");

        peopleList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(peopleList);

        fileMenu.setText("File");

        jMenuItem1.setText("Quit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        fileMenu.add(jMenuItem1);

        jMenuBar1.add(fileMenu);

        editMenu.setText("Edit");

        changeUsernameMenuItem.setText("Change Username");
        changeUsernameMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeUsernameMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(changeUsernameMenuItem);

        changeServerMenuItem.setText("Change Server");
        changeServerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeServerMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(changeServerMenuItem);

        jMenuBar1.add(editMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusBarLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(messageTextField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sendButton))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(messageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sendButton)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusBarLabel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        ChatMessage m = new ChatMessage(messageTextField.getText(), connection.getSelf().getName());
        try {
            connection.sendObject(m);
            messageTextField.setText("");
        } catch (IOException ex) {
            Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_sendButtonActionPerformed

    private void changeUsernameMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeUsernameMenuItemActionPerformed
        try {
            String newName = JOptionPane.showInputDialog(this, "Please enter your username.");
            System.out.println(newName == "null");
            connection.setSelf(new ChatPerson(newName, "online"));
            System.out.println("USERNAME " + connection.getSelf().getName());
            if (connection.getSelf() == null) {
                System.out.println("hi");
                changeUsernameMenuItemActionPerformed(evt);
            }
        } catch (IOException ex) {
            Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_changeUsernameMenuItemActionPerformed

    private void changeServerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeServerMenuItemActionPerformed
        try {
            String address = JOptionPane.showInputDialog(this, "Server address:");
            connection.setServer(address, 3191);
            statusBarLabel.setText("Connected to " + connection.getHost() + " as " + connection.getSelf().getName());
        } catch (UnknownHostException ex) {
            Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_changeServerMenuItemActionPerformed

    private void messageTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_messageTextFieldKeyTyped
        if (evt.getKeyChar() == '\n') {
            sendButtonActionPerformed(null);
        } else if (!messageTextField.getText().equalsIgnoreCase("")) {
            try {
                connection.notifyTyping();
            } catch (IOException ex) {
                log.otherMessage("ERROR IOException while typing");
            }
        }
    }//GEN-LAST:event_messageTextFieldKeyTyped

    private void messageTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_messageTextFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_messageTextFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new MainGUI().setVisible(true);
                } catch (UnknownHostException ex) {
                    Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem changeServerMenuItem;
    private javax.swing.JMenuItem changeUsernameMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea mainTextArea;
    private javax.swing.JTextField messageTextField;
    private javax.swing.JList peopleList;
    private javax.swing.JButton sendButton;
    private javax.swing.JLabel statusBarLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        if (o instanceof ChatConnection) {
            if (arg instanceof ChatMessage) {
                // Display the message. It's from another user.
                mainTextArea.append(((ChatMessage) arg).getSender() + ": " + ((ChatMessage) arg).getMessage() + "\n");
                mainTextArea.setCaretPosition(mainTextArea.getDocument().getLength());
                log.messageReceived((ChatMessage) arg);
            } else if (arg instanceof ChatPerson) {
                // Notify us of user connection. TODO Also add user to list
                personLoggedIn((ChatPerson) arg);
            } else if (arg instanceof ServerMessage) {
                // Message from server. Display special message depending on contents.
                System.out.println("Server message received");
                ServerMessage message = (ServerMessage) arg;
                processMessage(message);
                log.serverMessageReceived((ServerMessage) arg);
            }
        }
    }

    private void initConnection() throws UnknownHostException, IOException {
        System.out.println("init connection");
        connection = new ChatConnection("localhost", 3191);
        connection.addObserver(this);
        Thread t = new Thread(connection);
        t.start();
        changeUsernameMenuItemActionPerformed(null);
        statusBarLabel.setText("Connected to " + connection.getHost() + " as " + connection.getSelf().getName());
    }

    private void processMessage(ServerMessage message) {
        if (message.getServerCode() == 1) {
            ChatPerson person = (ChatPerson) message.getData();
            System.out.println(person.getName());
        } else if (message.getServerCode() == 3) {
            System.out.println(((ChatPerson) message.getData()).getName() + " has logged in");
            personLoggedIn((ChatPerson) message.getData());
        } else if (message.getServerCode() == 4) {
            ChatPerson person = (ChatPerson) message.getData();
            personIsTyping(person);
        }
    }

    private void personLoggedIn(ChatPerson chatPerson) {
        mainTextArea.append(((ChatPerson) chatPerson).getName() + " has entered\n");
        mainTextArea.setCaretPosition(mainTextArea.getDocument().getLength());
        people.add(chatPerson);
        updatePeopleList();
        log.personLoggedIn((ChatPerson) chatPerson);
    }

    private void updatePeopleList() {
        peopleList.setListData(people.toArray());
    }

    private void personIsTyping(ChatPerson person) {
        mainTextArea.append(((ChatPerson) person).getName() + " is typing\n");
        mainTextArea.setCaretPosition(mainTextArea.getDocument().getLength());
    }
}
